USE [master]
GO

/****** Object:  Database [Books]    Script Date: 15.7.2015 г. 16:43:42 ч. ******/
CREATE DATABASE [Books]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Books', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS2012\MSSQL\DATA\Books.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Books_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS2012\MSSQL\DATA\Books_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Books] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Books].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Books] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [Books] SET ANSI_NULLS ON 
GO

ALTER DATABASE [Books] SET ANSI_PADDING ON 
GO

ALTER DATABASE [Books] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [Books] SET ARITHABORT ON 
GO

ALTER DATABASE [Books] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Books] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Books] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Books] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Books] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Books] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [Books] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [Books] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Books] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [Books] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Books] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Books] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Books] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Books] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Books] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Books] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Books] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Books] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Books] SET RECOVERY FULL 
GO

ALTER DATABASE [Books] SET  MULTI_USER 
GO

ALTER DATABASE [Books] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [Books] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Books] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Books] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Books] SET  READ_WRITE 
GO

